name: ${COMPOSE_PROJECT_NAME}

services:
  postgres:
    image: postgres:18.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: slices
    ports:
      - "${PG_PORT}:5432"

  redis:
    image: redis:8.2-alpine
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  postgres_data:
